### ISSUE TITLE
Soundcloud einbetten ohne Extrabild

### ISSUE THREAD

**Issue by ToreVamos** [reedu-reengineering-education/mapstories#10]
Ich habe in der Story https://uploads.mapstories.de/uploads.mapstories.de/mapstories/140dfa4d-4aa6-4a50-a015-a39ee9cd9993/test-3/draft.html

auf Seite 4 "Leben im Vorort" eine Soundclouddatei eingebaut. Die Darstellung hat jedoch nur geklappt, wenn ich weiteres Bild eingefügt habe. Das braucht es eigentlich nicht. Was braucht es, damit nur eine Sounddatei eingebaut werden kann?
Danke
Tore

**Comment by umut0** [comment]
Werde ich mir anschauen. Kann ich nicht auf anhieb sagen.

**Comment by ToreVamos** [comment]
Alles klar, das gilt auch für GIFs

**Comment by umut0** [comment]
#18 Wenn man den Link in das Feld oben einfügt sollte es jetzt gehen.
