### ISSUE TITLE
Padlet einbetten

### ISSUE THREAD

**Issue by ToreVamos** [reedu-reengineering-education/mapstories#12]
Hej,
in der Story "Weg eines T-Shirts" wollen wir ein Padlet einbetten. Die Anzeige funktioniert bislang nicht.

Hier der Code:
<div class="padlet-embed" style="border:1px solid rgba(0,0,0,0.1);border-radius:2px;box-sizing:border-box;overflow:hidden;position:relative;width:100%;background:#F4F4F4"><p style="padding:0;margin:0"><iframe src="https://padlet.com/embed/b53gh89jridi6gie" frameborder="0" allow="camera;microphone;geolocation" style="width:100%;height:608px;display:block;padding:0;margin:0"></iframe></p><div style="padding:8px;text-align:right;margin:0;"><a href="https://padlet.com?ref=embed" style="padding:0;margin:0;border:none;display:block;line-height:1;height:16px" target="_blank"><img src="https://padlet.net/embeds/made_with_padlet.png" width="86" height="16" style="padding:0;margin:0;background:none;border:none;display:inline;box-shadow:none" alt="Mit Padlet erstellt"></a></div></div>

und hier der Link: 
https://padlet.com/VamosMuenster/b53gh89jridi6gie

Danke euch
ZT

**Comment by robarto** [comment]
s. issue #17
