### ISSUE TITLE
Einbettung Instragram

### ISSUE THREAD

**Issue by ToreVamos** [reedu-reengineering-education/mapstories#13]
Hej,

bei mir klappt die Einbettung von Insta nur soweit, als das ein leeres Insta-Bild erscheint mit dem Hinweis "Sieh dir den Beitrag auf Instagram" an. 
Ein Beispiel in der Story "Weg eines T-Shirts" auf Seite 7 "Garnhauptstadt".

Danke für eure Hilfe

**Comment by robarto** [comment]
Das hat bereits funktioniert. Wir haben nichts am Code geändert. Aber ich sehe das Problem nun auch. Wir finden dazu verschiedene Meldungen, dass das durch Instagram in bestimmten Webseiten geblockt wird. 

wir haben schon einen workaround gefunden. Mit dem einbettungscode gehts:
<iframe src='//instagram.com/p/CRnsuZkqx_y/embed/' width="500" height="600" frameborder="0"></iframe>

Der setzt sich zusammen aus der URL zu dem Post und "/embed" dahinter und dann Größeneingaben. 

Wir können beim nächsten Meeting gemeinsam überlegen, wie wir das vereinfachen könnten.

**Comment by robarto** [comment]
s. issue #17
