### ISSUE TITLE
Feedbackbutton für Externe auch bei öffentlichen Storys möglich, die wir zur Rückmeldung verschicken?

### ISSUE THREAD

**Issue by ToreVamos** [reedu-reengineering-education/mapstories#14]
Hej,
wir versenden die Storys gerade an verschiedene Leute um Rückmeldungen zu bekommen. Jetzt fiel mir auf, dass der Feedbackbutton nur sichtbar ist, wenn jemand angemeldet ist. Ist es möglich den Button aktuell für alle sichtbar zu machen? Dann können wir einfacher Rückmeldungen bekommen.

**Comment by umut0** [comment]
#18 Feedback button ist jetzt in jeder Story oben zu sehen
