### ISSUE TITLE
Vamos Cloud eingerichtet

### ISSUE THREAD

**Issue by ToreVamos** [reedu-reengineering-education/mapstories#15]
Wir haben jetzt den Cloud-Zugang für die Audiodateien.
https://cloud.vamos-muenster.de 

1. Wie kann ich euch sicher das Passwort zukommen lassen? 

2. Würdet ihr die Nextcloud so einrichten , dass zumindest Audios dort abgelegt werden können?

**Comment by robarto** [comment]
ist besprochen. kann geschlossen werden
