### ISSUE TITLE
MP3 upload

### ISSUE THREAD

**Issue by robarto** [reedu-reengineering-education/mapstories#16]
neben "Bild hochladen" soll ein "MP3 hochladen" button. 
MP3 auf 10MB beschränken. 
Upload in den user ordner. 
Abspielen über den Browser-seitigen Player (Felix weiß Bescheid)

**Comment by umut0** [comment]
MP3 Upload ist jetzt möglich. Bitte testen und Feedback.

**Comment by umut0** [comment]
Normalerweise hat jede slide nur 1 Medien Typ, also Mp3 oder Bild oder Vimeo etc.....
Ich gucke mal wie kompliziert es ist Mp3 und Bild in einer slide zu haben.

**Comment by ToreVamos** [comment]
Wie ist der aktuelle Stand Bild und Sound gleichzeitig?

**Comment by robarto** [comment]
wird jetzt als 1. Priorität gelöst.

**Comment by umut0** [comment]
Mp3 + Medium (e.g. Bild o.ä.) ist jetzt möglich
